export const staticDestinationPlaceSets = [
  {
    key: 'ahmedabad',
    aliases: ['ahmedabad', 'amdavad', 'ahmedabad gujarat'],
    places: [
      { name: 'Sabarmati Ashram', categoryLabel: 'heritage', address: 'Ashram Road, Ahmedabad, Gujarat, India', latOffset: 0.022, lonOffset: -0.018, distanceMeters: 3200 },
      { name: 'Sidi Saiyyed ni Jali', categoryLabel: 'heritage', address: 'Lal Darwaja, Ahmedabad, Gujarat, India', latOffset: 0.004, lonOffset: 0.002, distanceMeters: 700 },
      { name: 'Sabarmati Riverfront', categoryLabel: 'riverfront', address: 'Sabarmati Riverfront, Ahmedabad, Gujarat, India', latOffset: 0.008, lonOffset: -0.006, distanceMeters: 1200 },
      { name: 'Manek Chowk', categoryLabel: 'street food', address: 'Old City, Ahmedabad, Gujarat, India', latOffset: 0.003, lonOffset: 0.008, distanceMeters: 950 },
      { name: 'Adalaj Stepwell', categoryLabel: 'stepwell', address: 'Adalaj, Gandhinagar, Gujarat, India', latOffset: 0.19, lonOffset: 0.04, distanceMeters: 19200 },
      { name: 'Kankaria Lake', categoryLabel: 'lake', address: 'Kankaria, Ahmedabad, Gujarat, India', latOffset: -0.03, lonOffset: 0.02, distanceMeters: 4200 },
      { name: 'Jama Masjid Ahmedabad', categoryLabel: 'heritage', address: 'Manek Chowk, Ahmedabad, Gujarat, India', latOffset: 0.002, lonOffset: 0.006, distanceMeters: 850 },
      { name: 'Teen Darwaza', categoryLabel: 'landmark', address: 'Bhadra, Ahmedabad, Gujarat, India', latOffset: 0.001, lonOffset: 0.005, distanceMeters: 760 },
      { name: 'Law Garden Night Market', categoryLabel: 'shopping', address: 'Law Garden, Ahmedabad, Gujarat, India', latOffset: 0.012, lonOffset: -0.004, distanceMeters: 1800 },
      { name: 'Atal Bridge', categoryLabel: 'riverfront', address: 'Sabarmati Riverfront, Ahmedabad, Gujarat, India', latOffset: 0.009, lonOffset: -0.008, distanceMeters: 1350 },
    ],
  },
  {
    key: 'goa',
    aliases: ['goa', 'panaji', 'margao', 'calangute', 'old goa', 'north goa', 'south goa'],
    places: [
      { name: 'Baga Beach', categoryLabel: 'beach', address: 'Bardez, Goa, India', latOffset: 0.07, lonOffset: 0.09, distanceMeters: 8200 },
      { name: 'Calangute Beach', categoryLabel: 'beach', address: 'Calangute, Goa, India', latOffset: 0.06, lonOffset: 0.075, distanceMeters: 6800 },
      { name: 'Basilica of Bom Jesus', categoryLabel: 'heritage', address: 'Old Goa, Goa, India', latOffset: 0.02, lonOffset: 0.015, distanceMeters: 2400 },
      { name: 'Fort Aguada', categoryLabel: 'fort', address: 'Candolim, Goa, India', latOffset: 0.08, lonOffset: 0.04, distanceMeters: 7600 },
      { name: 'Chapora Fort', categoryLabel: 'viewpoint', address: 'Chapora, Goa, India', latOffset: 0.095, lonOffset: 0.085, distanceMeters: 9800 },
      { name: 'Anjuna Flea Market', categoryLabel: 'market', address: 'Anjuna, Goa, India', latOffset: 0.072, lonOffset: 0.082, distanceMeters: 8500 },
      { name: 'Dona Paula View Point', categoryLabel: 'viewpoint', address: 'Dona Paula, Goa, India', latOffset: -0.01, lonOffset: 0.03, distanceMeters: 2200 },
      { name: 'Fontainhas', categoryLabel: 'heritage quarter', address: 'Panaji, Goa, India', latOffset: 0.004, lonOffset: 0.008, distanceMeters: 900 },
      { name: 'Miramar Beach', categoryLabel: 'beach', address: 'Panaji, Goa, India', latOffset: -0.006, lonOffset: 0.018, distanceMeters: 1500 },
      { name: 'Candolim Beach', categoryLabel: 'beach', address: 'Candolim, Goa, India', latOffset: 0.065, lonOffset: 0.05, distanceMeters: 6900 },
    ],
  },
  {
    key: 'kerala',
    aliases: ['kerala', 'kochi', 'cochin', 'munnar', 'alleppey', 'alappuzha', 'varkala', 'wayanad', 'trivandrum'],
    places: [
      { name: 'Alleppey Backwaters', categoryLabel: 'nature', address: 'Alappuzha, Kerala, India', latOffset: 0.05, lonOffset: 0.03, distanceMeters: 5100 },
      { name: 'Munnar Tea Plantations', categoryLabel: 'nature', address: 'Munnar, Kerala, India', latOffset: 0.08, lonOffset: -0.05, distanceMeters: 9300 },
      { name: 'Varkala Beach', categoryLabel: 'beach', address: 'Varkala, Kerala, India', latOffset: -0.07, lonOffset: 0.05, distanceMeters: 8400 },
      { name: 'Periyar Wildlife Sanctuary', categoryLabel: 'wildlife', address: 'Thekkady, Kerala, India', latOffset: 0.03, lonOffset: -0.08, distanceMeters: 7600 },
      { name: 'Mattancherry Palace', categoryLabel: 'heritage', address: 'Kochi, Kerala, India', latOffset: 0.012, lonOffset: 0.016, distanceMeters: 1800 },
      { name: 'Fort Kochi Beach', categoryLabel: 'beachfront', address: 'Fort Kochi, Kerala, India', latOffset: 0.01, lonOffset: 0.018, distanceMeters: 2100 },
      { name: 'Chinese Fishing Nets', categoryLabel: 'landmark', address: 'Fort Kochi, Kerala, India', latOffset: 0.009, lonOffset: 0.017, distanceMeters: 2000 },
      { name: 'Athirappilly Waterfalls', categoryLabel: 'waterfall', address: 'Thrissur, Kerala, India', latOffset: 0.11, lonOffset: -0.02, distanceMeters: 12800 },
      { name: 'Kumarakom Bird Sanctuary', categoryLabel: 'nature', address: 'Kottayam, Kerala, India', latOffset: 0.035, lonOffset: 0.02, distanceMeters: 4400 },
      { name: 'Cherai Beach', categoryLabel: 'beach', address: 'Ernakulam, Kerala, India', latOffset: 0.028, lonOffset: 0.03, distanceMeters: 3600 },
    ],
  },
  {
    key: 'manali',
    aliases: ['manali', 'kullu', 'solang', 'rohtang'],
    places: [
      { name: 'Hadimba Temple', categoryLabel: 'spiritual', address: 'Old Manali, Himachal Pradesh, India', latOffset: 0.01, lonOffset: -0.008, distanceMeters: 1200 },
      { name: 'Solang Valley', categoryLabel: 'adventure', address: 'Solang Valley, Himachal Pradesh, India', latOffset: 0.11, lonOffset: 0.02, distanceMeters: 13200 },
      { name: 'Rohtang Pass', categoryLabel: 'mountain pass', address: 'Rohtang, Himachal Pradesh, India', latOffset: 0.18, lonOffset: 0.05, distanceMeters: 20800 },
      { name: 'Jogini Waterfall', categoryLabel: 'waterfall', address: 'Vashisht, Himachal Pradesh, India', latOffset: 0.03, lonOffset: 0.014, distanceMeters: 3200 },
      { name: 'Old Manali Café Street', categoryLabel: 'local culture', address: 'Old Manali, Himachal Pradesh, India', latOffset: 0.014, lonOffset: -0.005, distanceMeters: 1500 },
      { name: 'Vashisht Hot Springs', categoryLabel: 'wellness', address: 'Vashisht, Himachal Pradesh, India', latOffset: 0.022, lonOffset: 0.01, distanceMeters: 2500 },
      { name: 'Manu Temple', categoryLabel: 'heritage', address: 'Old Manali, Himachal Pradesh, India', latOffset: 0.018, lonOffset: -0.004, distanceMeters: 2100 },
      { name: 'Nehru Kund', categoryLabel: 'nature', address: 'Manali, Himachal Pradesh, India', latOffset: 0.04, lonOffset: 0.01, distanceMeters: 4700 },
      { name: 'Mall Road Manali', categoryLabel: 'market', address: 'Manali, Himachal Pradesh, India', latOffset: 0.004, lonOffset: 0.005, distanceMeters: 700 },
      { name: 'Club House Manali', categoryLabel: 'family activity', address: 'Old Manali, Himachal Pradesh, India', latOffset: 0.012, lonOffset: 0.002, distanceMeters: 1500 },
    ],
  },
  {
    key: 'jaipur',
    aliases: ['jaipur', 'rajasthan'],
    places: [
      { name: 'Amber Fort', categoryLabel: 'heritage', address: 'Amer, Jaipur, Rajasthan, India', latOffset: 0.06, lonOffset: 0.05, distanceMeters: 8600 },
      { name: 'Hawa Mahal', categoryLabel: 'heritage', address: 'Pink City, Jaipur, Rajasthan, India', latOffset: 0.01, lonOffset: 0.012, distanceMeters: 1400 },
      { name: 'City Palace Jaipur', categoryLabel: 'culture', address: 'Jaipur, Rajasthan, India', latOffset: 0.012, lonOffset: 0.01, distanceMeters: 1600 },
      { name: 'Jal Mahal', categoryLabel: 'lake palace', address: 'Amer Road, Jaipur, Rajasthan, India', latOffset: 0.03, lonOffset: 0.025, distanceMeters: 4100 },
      { name: 'Jantar Mantar Jaipur', categoryLabel: 'observatory', address: 'Jaipur, Rajasthan, India', latOffset: 0.011, lonOffset: 0.011, distanceMeters: 1500 },
      { name: 'Nahargarh Fort', categoryLabel: 'viewpoint', address: 'Jaipur, Rajasthan, India', latOffset: 0.032, lonOffset: 0.016, distanceMeters: 4900 },
      { name: 'Patrika Gate', categoryLabel: 'landmark', address: 'Jawahar Circle, Jaipur, Rajasthan, India', latOffset: -0.04, lonOffset: 0.03, distanceMeters: 6200 },
      { name: 'Johari Bazaar', categoryLabel: 'market', address: 'Jaipur, Rajasthan, India', latOffset: 0.009, lonOffset: 0.013, distanceMeters: 1300 },
      { name: 'Albert Hall Museum', categoryLabel: 'museum', address: 'Ram Niwas Garden, Jaipur, Rajasthan, India', latOffset: 0.006, lonOffset: 0.008, distanceMeters: 950 },
      { name: 'Panna Meena ka Kund', categoryLabel: 'stepwell', address: 'Amer, Jaipur, Rajasthan, India', latOffset: 0.058, lonOffset: 0.048, distanceMeters: 8100 },
    ],
  },
  {
    key: 'varanasi',
    aliases: ['varanasi', 'banaras', 'kashi'],
    places: [
      { name: 'Dashashwamedh Ghat', categoryLabel: 'spiritual', address: 'Varanasi, Uttar Pradesh, India', latOffset: 0.006, lonOffset: 0.004, distanceMeters: 800 },
      { name: 'Kashi Vishwanath Temple', categoryLabel: 'heritage', address: 'Varanasi, Uttar Pradesh, India', latOffset: 0.008, lonOffset: 0.006, distanceMeters: 950 },
      { name: 'Assi Ghat', categoryLabel: 'spiritual', address: 'Varanasi, Uttar Pradesh, India', latOffset: -0.018, lonOffset: -0.004, distanceMeters: 2300 },
      { name: 'Sarnath', categoryLabel: 'historical', address: 'Sarnath, Uttar Pradesh, India', latOffset: 0.08, lonOffset: 0.04, distanceMeters: 9800 },
      { name: 'Manikarnika Ghat View', categoryLabel: 'heritage', address: 'Varanasi, Uttar Pradesh, India', latOffset: 0.009, lonOffset: 0.005, distanceMeters: 1100 },
      { name: 'Ramnagar Fort', categoryLabel: 'fort', address: 'Ramnagar, Varanasi, Uttar Pradesh, India', latOffset: 0.03, lonOffset: 0.028, distanceMeters: 4200 },
      { name: 'Banaras Hindu University Gate', categoryLabel: 'landmark', address: 'Varanasi, Uttar Pradesh, India', latOffset: -0.026, lonOffset: -0.008, distanceMeters: 3200 },
      { name: 'Tulsi Ghat', categoryLabel: 'spiritual', address: 'Varanasi, Uttar Pradesh, India', latOffset: -0.02, lonOffset: -0.005, distanceMeters: 2400 },
      { name: 'Godowlia Market', categoryLabel: 'market', address: 'Varanasi, Uttar Pradesh, India', latOffset: 0.004, lonOffset: 0.004, distanceMeters: 650 },
      { name: 'Banarasi Silk Lane', categoryLabel: 'shopping', address: 'Varanasi, Uttar Pradesh, India', latOffset: 0.005, lonOffset: 0.007, distanceMeters: 780 },
    ],
  },
  {
    key: 'haridwar',
    aliases: ['haridwar'],
    places: [
      { name: 'Har Ki Pauri', categoryLabel: 'spiritual', address: 'Haridwar, Uttarakhand, India', latOffset: 0.004, lonOffset: 0.003, distanceMeters: 650 },
      { name: 'Mansa Devi Temple', categoryLabel: 'spiritual', address: 'Bilwa Parvat, Haridwar, Uttarakhand, India', latOffset: 0.018, lonOffset: 0.008, distanceMeters: 2100 },
      { name: 'Chandi Devi Temple', categoryLabel: 'spiritual', address: 'Neel Parvat, Haridwar, Uttarakhand, India', latOffset: 0.022, lonOffset: 0.016, distanceMeters: 2800 },
      { name: 'Daksh Mahadev Temple', categoryLabel: 'spiritual', address: 'Kankhal, Haridwar, Uttarakhand, India', latOffset: -0.028, lonOffset: 0.01, distanceMeters: 3900 },
      { name: 'Bharat Mata Mandir', categoryLabel: 'landmark', address: 'Haridwar, Uttarakhand, India', latOffset: 0.012, lonOffset: 0.007, distanceMeters: 1500 },
      { name: 'Shantikunj', categoryLabel: 'wellness', address: 'Haridwar, Uttarakhand, India', latOffset: 0.03, lonOffset: 0.02, distanceMeters: 4300 },
      { name: 'Rajaji National Park Gate', categoryLabel: 'nature', address: 'Haridwar, Uttarakhand, India', latOffset: -0.035, lonOffset: -0.02, distanceMeters: 5200 },
      { name: 'Sapt Rishi Ashram', categoryLabel: 'spiritual', address: 'Haridwar, Uttarakhand, India', latOffset: 0.025, lonOffset: 0.012, distanceMeters: 3400 },
      { name: 'Maya Devi Temple', categoryLabel: 'spiritual', address: 'Haridwar, Uttarakhand, India', latOffset: 0.006, lonOffset: 0.005, distanceMeters: 980 },
      { name: 'Haridwar Ganga Aarti View', categoryLabel: 'river ritual', address: 'Har Ki Pauri, Haridwar, Uttarakhand, India', latOffset: 0.005, lonOffset: 0.004, distanceMeters: 720 },
    ],
  },
  {
    key: 'rishikesh',
    aliases: ['rishikesh', 'uttarakhand'],
    places: [
      { name: 'Laxman Jhula', categoryLabel: 'landmark', address: 'Tapovan, Rishikesh, Uttarakhand, India', latOffset: 0.02, lonOffset: 0.015, distanceMeters: 2200 },
      { name: 'Triveni Ghat', categoryLabel: 'spiritual', address: 'Rishikesh, Uttarakhand, India', latOffset: -0.008, lonOffset: 0.004, distanceMeters: 900 },
      { name: 'Beatles Ashram', categoryLabel: 'culture', address: 'Swarg Ashram, Rishikesh, Uttarakhand, India', latOffset: 0.012, lonOffset: 0.01, distanceMeters: 1600 },
      { name: 'Neer Garh Waterfall', categoryLabel: 'nature', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.035, lonOffset: 0.02, distanceMeters: 4200 },
      { name: 'Ram Jhula', categoryLabel: 'landmark', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.008, lonOffset: 0.008, distanceMeters: 1200 },
      { name: 'Parmarth Niketan', categoryLabel: 'wellness', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.007, lonOffset: 0.007, distanceMeters: 1050 },
      { name: 'Tapovan Café Belt', categoryLabel: 'cafe district', address: 'Tapovan, Rishikesh, Uttarakhand, India', latOffset: 0.018, lonOffset: 0.013, distanceMeters: 2000 },
      { name: 'Kaudiyala Rafting Stretch', categoryLabel: 'adventure', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.08, lonOffset: 0.03, distanceMeters: 9200 },
      { name: 'Ganga Beach Rishikesh', categoryLabel: 'riverfront', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.01, lonOffset: 0.009, distanceMeters: 1400 },
      { name: 'Shivpuri View Point', categoryLabel: 'viewpoint', address: 'Rishikesh, Uttarakhand, India', latOffset: 0.05, lonOffset: 0.02, distanceMeters: 6100 },
    ],
  },
  {
    key: 'shimla',
    aliases: ['shimla', 'himachal pradesh'],
    places: [
      { name: 'Mall Road', categoryLabel: 'market', address: 'Shimla, Himachal Pradesh, India', latOffset: 0.004, lonOffset: 0.006, distanceMeters: 600 },
      { name: 'Jakhoo Temple', categoryLabel: 'spiritual', address: 'Shimla, Himachal Pradesh, India', latOffset: 0.016, lonOffset: 0.005, distanceMeters: 1800 },
      { name: 'Christ Church', categoryLabel: 'heritage', address: 'The Ridge, Shimla, Himachal Pradesh, India', latOffset: 0.003, lonOffset: 0.008, distanceMeters: 700 },
      { name: 'Kufri', categoryLabel: 'hill station', address: 'Kufri, Himachal Pradesh, India', latOffset: 0.12, lonOffset: 0.04, distanceMeters: 13600 },
    ],
  },
  {
    key: 'agra',
    aliases: ['agra'],
    places: [
      { name: 'Taj Mahal', categoryLabel: 'monument', address: 'Agra, Uttar Pradesh, India', latOffset: 0.01, lonOffset: 0.008, distanceMeters: 1200 },
      { name: 'Agra Fort', categoryLabel: 'fort', address: 'Agra, Uttar Pradesh, India', latOffset: 0.006, lonOffset: -0.012, distanceMeters: 1500 },
      { name: 'Mehtab Bagh', categoryLabel: 'garden', address: 'Agra, Uttar Pradesh, India', latOffset: 0.015, lonOffset: 0.018, distanceMeters: 2200 },
      { name: 'Fatehpur Sikri', categoryLabel: 'heritage', address: 'Fatehpur Sikri, Uttar Pradesh, India', latOffset: 0.16, lonOffset: -0.08, distanceMeters: 23500 },
    ],
  },
  {
    key: 'udaipur',
    aliases: ['udaipur'],
    places: [
      { name: 'Lake Pichola', categoryLabel: 'lake', address: 'Udaipur, Rajasthan, India', latOffset: 0.006, lonOffset: 0.006, distanceMeters: 900 },
      { name: 'City Palace Udaipur', categoryLabel: 'heritage', address: 'Udaipur, Rajasthan, India', latOffset: 0.008, lonOffset: 0.008, distanceMeters: 1100 },
      { name: 'Jag Mandir', categoryLabel: 'lake palace', address: 'Udaipur, Rajasthan, India', latOffset: 0.012, lonOffset: 0.01, distanceMeters: 1600 },
      { name: 'Sajjangarh Palace', categoryLabel: 'viewpoint', address: 'Udaipur, Rajasthan, India', latOffset: 0.028, lonOffset: -0.02, distanceMeters: 4100 },
      { name: 'Bagore Ki Haveli', categoryLabel: 'heritage', address: 'Udaipur, Rajasthan, India', latOffset: 0.007, lonOffset: 0.007, distanceMeters: 980 },
      { name: 'Fateh Sagar Lake', categoryLabel: 'lake', address: 'Udaipur, Rajasthan, India', latOffset: 0.015, lonOffset: -0.002, distanceMeters: 2100 },
      { name: 'Gangaur Ghat', categoryLabel: 'lakefront', address: 'Udaipur, Rajasthan, India', latOffset: 0.006, lonOffset: 0.009, distanceMeters: 920 },
      { name: 'Saheliyon Ki Bari', categoryLabel: 'garden', address: 'Udaipur, Rajasthan, India', latOffset: 0.018, lonOffset: -0.003, distanceMeters: 2500 },
      { name: 'Ambrai Ghat', categoryLabel: 'sunset', address: 'Udaipur, Rajasthan, India', latOffset: 0.005, lonOffset: 0.005, distanceMeters: 760 },
      { name: 'Shilpgram Udaipur', categoryLabel: 'craft village', address: 'Udaipur, Rajasthan, India', latOffset: 0.04, lonOffset: -0.025, distanceMeters: 5600 },
    ],
  },
  {
    key: 'darjeeling',
    aliases: ['darjeeling'],
    places: [
      { name: 'Tiger Hill', categoryLabel: 'viewpoint', address: 'Darjeeling, West Bengal, India', latOffset: 0.05, lonOffset: 0.03, distanceMeters: 6400 },
      { name: 'Batasia Loop', categoryLabel: 'landmark', address: 'Darjeeling, West Bengal, India', latOffset: 0.014, lonOffset: 0.012, distanceMeters: 1800 },
      { name: 'Darjeeling Himalayan Railway', categoryLabel: 'heritage', address: 'Darjeeling, West Bengal, India', latOffset: 0.008, lonOffset: 0.006, distanceMeters: 1000 },
      { name: 'Japanese Peace Pagoda', categoryLabel: 'spiritual', address: 'Darjeeling, West Bengal, India', latOffset: 0.018, lonOffset: 0.014, distanceMeters: 2300 },
    ],
  },
  {
    key: 'leh ladakh',
    aliases: ['leh ladakh', 'ladakh', 'leh', 'kargil'],
    places: [
      { name: 'Shanti Stupa', categoryLabel: 'viewpoint', address: 'Leh, Ladakh, India', latOffset: 0.01, lonOffset: 0.01, distanceMeters: 1200 },
      { name: 'Leh Palace', categoryLabel: 'heritage', address: 'Leh, Ladakh, India', latOffset: 0.008, lonOffset: 0.012, distanceMeters: 1100 },
      { name: 'Pangong Lake', categoryLabel: 'lake', address: 'Ladakh, India', latOffset: 0.15, lonOffset: 0.08, distanceMeters: 28500 },
      { name: 'Nubra Valley', categoryLabel: 'valley', address: 'Ladakh, India', latOffset: 0.11, lonOffset: -0.07, distanceMeters: 21400 },
      { name: 'Hall of Fame', categoryLabel: 'museum', address: 'Leh, Ladakh, India', latOffset: 0.012, lonOffset: 0.008, distanceMeters: 1400 },
      { name: 'Leh Main Bazaar', categoryLabel: 'market', address: 'Leh, Ladakh, India', latOffset: 0.006, lonOffset: 0.01, distanceMeters: 900 },
      { name: 'Magnetic Hill', categoryLabel: 'landscape', address: 'Leh, Ladakh, India', latOffset: 0.05, lonOffset: -0.02, distanceMeters: 6200 },
      { name: 'Thiksey Monastery', categoryLabel: 'monastery', address: 'Leh, Ladakh, India', latOffset: 0.04, lonOffset: 0.03, distanceMeters: 5400 },
      { name: 'Sangam View', categoryLabel: 'viewpoint', address: 'Leh, Ladakh, India', latOffset: 0.06, lonOffset: -0.03, distanceMeters: 7600 },
      { name: 'Diskit Monastery', categoryLabel: 'monastery', address: 'Nubra Valley, Ladakh, India', latOffset: 0.1, lonOffset: -0.06, distanceMeters: 19800 },
    ],
  },
  {
    key: 'spiti valley',
    aliases: ['spiti valley', 'spiti', 'kaza', 'tabo', 'chandratal'],
    places: [
      { name: 'Key Monastery', categoryLabel: 'monastery', address: 'Kaza, Spiti Valley, Himachal Pradesh, India', latOffset: 0.03, lonOffset: 0.018, distanceMeters: 4200 },
      { name: 'Kibber Village', categoryLabel: 'village', address: 'Kibber, Spiti Valley, Himachal Pradesh, India', latOffset: 0.05, lonOffset: 0.028, distanceMeters: 6900 },
      { name: 'Langza Buddha', categoryLabel: 'viewpoint', address: 'Langza, Spiti Valley, Himachal Pradesh, India', latOffset: 0.045, lonOffset: 0.012, distanceMeters: 6100 },
      { name: 'Hikkim Post Office', categoryLabel: 'landmark', address: 'Hikkim, Spiti Valley, Himachal Pradesh, India', latOffset: 0.041, lonOffset: 0.014, distanceMeters: 5600 },
      { name: 'Komic Village', categoryLabel: 'village', address: 'Komic, Spiti Valley, Himachal Pradesh, India', latOffset: 0.048, lonOffset: 0.016, distanceMeters: 6400 },
      { name: 'Tabo Monastery', categoryLabel: 'monastery', address: 'Tabo, Spiti Valley, Himachal Pradesh, India', latOffset: -0.08, lonOffset: -0.022, distanceMeters: 11600 },
      { name: 'Dhankar Monastery', categoryLabel: 'monastery', address: 'Dhankar, Spiti Valley, Himachal Pradesh, India', latOffset: -0.03, lonOffset: -0.01, distanceMeters: 4800 },
      { name: 'Chicham Bridge', categoryLabel: 'bridge viewpoint', address: 'Chicham, Spiti Valley, Himachal Pradesh, India', latOffset: 0.054, lonOffset: 0.025, distanceMeters: 7200 },
      { name: 'Pin Valley View', categoryLabel: 'valley', address: 'Pin Valley, Spiti Valley, Himachal Pradesh, India', latOffset: -0.035, lonOffset: 0.02, distanceMeters: 5300 },
      { name: 'Chandratal Lake', categoryLabel: 'lake', address: 'Chandratal, Himachal Pradesh, India', latOffset: 0.12, lonOffset: -0.035, distanceMeters: 18500 },
    ],
  },
  {
    key: 'amritsar',
    aliases: ['amritsar'],
    places: [
      { name: 'Golden Temple', categoryLabel: 'spiritual', address: 'Amritsar, Punjab, India', latOffset: 0.006, lonOffset: 0.006, distanceMeters: 800 },
      { name: 'Jallianwala Bagh', categoryLabel: 'historical', address: 'Amritsar, Punjab, India', latOffset: 0.007, lonOffset: 0.005, distanceMeters: 950 },
      { name: 'Partition Museum', categoryLabel: 'museum', address: 'Amritsar, Punjab, India', latOffset: 0.01, lonOffset: 0.008, distanceMeters: 1300 },
      { name: 'Wagah Border', categoryLabel: 'border ceremony', address: 'Amritsar, Punjab, India', latOffset: 0.19, lonOffset: 0.12, distanceMeters: 30200 },
    ],
  },
  {
    key: 'andaman',
    aliases: ['andaman', 'port blair', 'havelock island', 'swaraj dweep', 'andaman and nicobar islands'],
    places: [
      { name: 'Cellular Jail', categoryLabel: 'heritage', address: 'Port Blair, Andaman and Nicobar Islands, India', latOffset: 0.008, lonOffset: 0.006, distanceMeters: 900 },
      { name: 'Radhanagar Beach', categoryLabel: 'beach', address: 'Swaraj Dweep, Andaman and Nicobar Islands, India', latOffset: 0.07, lonOffset: 0.09, distanceMeters: 9200 },
      { name: 'Ross Island', categoryLabel: 'island', address: 'Port Blair, Andaman and Nicobar Islands, India', latOffset: 0.02, lonOffset: 0.018, distanceMeters: 2600 },
      { name: 'Corbyn’s Cove Beach', categoryLabel: 'beach', address: 'Port Blair, Andaman and Nicobar Islands, India', latOffset: 0.015, lonOffset: 0.012, distanceMeters: 1800 },
    ],
  },
  {
    key: 'jammu and kashmir',
    aliases: ['jammu and kashmir', 'kashmir', 'srinagar', 'gulmarg', 'pahalgam'],
    places: [
      { name: 'Dal Lake', categoryLabel: 'lake', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.012, lonOffset: 0.01, distanceMeters: 1400 },
      { name: 'Gulmarg Gondola', categoryLabel: 'adventure', address: 'Gulmarg, Jammu and Kashmir, India', latOffset: 0.09, lonOffset: -0.05, distanceMeters: 12600 },
      { name: 'Mughal Gardens', categoryLabel: 'garden', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.018, lonOffset: 0.015, distanceMeters: 2200 },
      { name: 'Betaab Valley', categoryLabel: 'nature', address: 'Pahalgam, Jammu and Kashmir, India', latOffset: 0.11, lonOffset: 0.07, distanceMeters: 16800 },
      { name: 'Shalimar Bagh', categoryLabel: 'garden', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.016, lonOffset: 0.016, distanceMeters: 2300 },
      { name: 'Nishat Bagh', categoryLabel: 'garden', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.017, lonOffset: 0.017, distanceMeters: 2400 },
      { name: 'Hazratbal Shrine', categoryLabel: 'spiritual', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.013, lonOffset: 0.015, distanceMeters: 1900 },
      { name: 'Pari Mahal', categoryLabel: 'viewpoint', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.022, lonOffset: 0.012, distanceMeters: 3100 },
      { name: 'Pahalgam Riverfront', categoryLabel: 'riverfront', address: 'Pahalgam, Jammu and Kashmir, India', latOffset: 0.1, lonOffset: 0.065, distanceMeters: 15400 },
      { name: 'Srinagar Old City Walk', categoryLabel: 'heritage quarter', address: 'Srinagar, Jammu and Kashmir, India', latOffset: 0.01, lonOffset: 0.008, distanceMeters: 1200 },
    ],
  },
];
